name: pose_camera_view
description: "Pose Camera view uses Google ML Kit to track your push-ups. It emits 'init', 'middle', and 'completed' events for each rep, and displays the total count."
version: 1.0.1
homepage: https://www.paolojoaquin.com
repository: https://github.com/paolojoaquinp/pose_camera_view_widget

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  camera: ^0.11.0+1
  flutter:
    sdk: flutter
  google_ml_kit: ^0.18.0

dev_dependencies:
  dart_code_linter: ^1.1.1
  dart_code_metrics: ^5.7.6
  very_good_analysis: ^6.0.0

screenshots:
  - description: Pose Camera Widget
    path: screenshots/pose_camera_view.gif
  - description: Pose Camera Widget
    path: screenshots/pose_camera_view.png
  - description: Pose Camera Widget
    path: screenshots/pose_camera_view1.gif

false_secrets:
  - /lib/*
  - /**/*

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg