name: pose_camera_view
description: "A new Flutter package project."
version: 1.0.0
homepage: https://www.d-velopers.com
repository: https://github.com/paolojoaquinp/pose_camera_view_widget

environment:
  sdk: '>=3.5.0-214.0.dev <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  camera: ^0.11.0+1
  flutter:
    sdk: flutter
  google_ml_kit: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

screenshots:
  - description: Pose Camera Widget
    path: screenshots/pose_camera_view.gif
  - description: Pose Camera Widget
    path: screenshots/pose_camera_view.png
  - description: Pose Camera Widget
    path: screenshots/pose_camera_view1.gif

false_secrets:
  - /lib/*
  - /**/*

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg